name: Check PR File Changes

on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  count_changed_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 1000

      - name: Fetch main branch
        run: git fetch origin main

      - name: Count changed files
        id: count
        run: |
          # Get the number of changed files
          FILES_CHANGED=$(git diff --name-only origin/main... | wc -l)
          echo "Changed files: $FILES_CHANGED"
          
          # Set the output variable
          echo "PR_FILES=$FILES_CHANGED" >> $GITHUB_ENV
      
      - name: Post a comment if PR exceeds 15 files
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        if: env.PR_FILES > 15
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "This PR contains **${{ env.PR_FILES }}** files, which is more than the allowed limit of 15 files. Please split it into smaller PRs for easier review."


      - name: Fail if more than 15 files changed
        run: |
          if [ ${{ env.PR_FILES }} -gt 15 ]; then
            echo "Error: More than 15 files changed in this PR. Please limit to 15 files or fewer."
            exit 1
          fi
